#!/bin/bash
dataset=$1  # path to dataset
result_name=$2

RESULT_DIR="results"

rm -rf "results/*"

dataset="../../dataset/wine.scale"
dim="13"
lambda="13"

for x in $(seq 100)
do
    mkdir results/$x
    ./sparseClustering $dataset $dim $lambda > sparseClustering.log
    cp opt* results/$x
    cp sparseClustering.log results/$x
done

