/*###############################################################
## MODULE: DP_MEDOIDS.h
## VERSION: 1.0 
## SINCE 2014-08-20
## AUTHOR Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
## DESCRIPTION: 
##     This file includes problem-specific data structure and
## utility function.
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

#include<iostream>
#include<fstream>
#include<stdlib.h>
#include<vector>
#include<map>
#include<set>
#include<algorithm>
#include <cmath>    
#include "../util.h"
#include "../mat.h"

using namespace std;

class Instance{
	
	public:
	int id;
	int label;
	vector<pair<int,double> > fea;
	Instance(int _id){
		id = _id;
		_x_sq = -1.0;
	}
	
	double x_sq(){
		
		// Pre-calculated
		if( _x_sq != -1.0 ){
			return _x_sq;
		}
		
		// Calculate and Cache
		_x_sq = 0.0;
		double tmp;
		for(int i=0;i<fea.size();i++){
			tmp = fea[i].second;
			_x_sq += tmp*tmp;
		}

		return _x_sq;
	}

	private:
	double _x_sq;
};

class Cluster{

	public:
	int d;
	vector<double>  mu;
	double mu_sq;

	Cluster(int _d){
		
		d = _d;
		for(int i=0;i<d+1;i++)
			mu.push_back( ((double)rand()/RAND_MAX)*2-1 );
		mu[0] = 0.0;
		mu_sq = -1;
	}

	Cluster(vector<double>& _mu){
		
		d = _mu.size()-1;
		for(int i=0;i<_mu.size();i++)
			mu.push_back( _mu[i] );
		mu_sq = -1;
	}
	
	double dist(Instance* ins){
		
		if( mu_sq == -1 ){
			mu_sq = 0.0;
			for(int i=0;i<d+1;i++){
				mu_sq += mu[i]*mu[i];
			}
		}
		
		return  ins->x_sq() + mu_sq - 2*dot(mu,ins->fea);
	}
};

class ScoreComparator{
	
	private:
	vector<double>* score_vec;

	public:
	ScoreComparator(vector<double>* vec){
		score_vec = vec;
	}

	bool operator() (int i,int j) { 
		return score_vec->at(i) < score_vec->at(j); 
	}
};


/** loss = \frac{1}{2} sum_{i,j}{ w_{ij}\| x_i - mu_j \|_2^2 },  w_{iz[i]}=1
 */
double obj_loss( vector<Instance*>& data, int* z, map<int,Cluster*>& clusters ){
	
	double loss = 0.0;
	for(int i=0;i<data.size();i++){
		
		Cluster* cluster = clusters.find( z[i] )->second;
		Instance* ins = data[i];

		loss += cluster->dist( ins )/2;
	}
	
	return loss;
}

void read2D(char* fname, vector<Instance*>& data){
	
	ifstream fin(fname);
	int tmp;
	double x,y;
	int id=0;
	while(!fin.eof()){
		
		fin >> tmp >> x >> y;
		if( fin.eof() )break;

		Instance* ins = new Instance(id++);
		ins->fea.push_back(make_pair(1,x));
		ins->fea.push_back(make_pair(2,y));
		
		data.push_back(ins);
	}
	fin.close();
}


void readFixDim(char* fname, vector<Instance*>& data, int D){
	
	ifstream fin(fname);
	int tmp;
	double val;
	int id=0;
	while(!fin.eof()){
		
		fin >> tmp;
		if( fin.eof() )break;
		
		Instance* ins = new Instance(id++);
	       	for(int j=0;j<D;j++){
			fin >> val;
			ins->fea.push_back(make_pair(j+1,val));
		}
		
		data.push_back(ins);
		id++;
	}
	fin.close();
}
