flag= -O3 -fopenmp -w

all:
	g++ $(flag)  TKF1.cpp -o TKF1
	g++ $(flag)  TKF1_multi.cpp -o TKF1_multi
	g++ $(flag)  estimate_TKF1.cpp -o estimate_TKF1
	g++ $(flag)  est_TKF1_noAlign.cpp -o est_TKF1_noAlign
